### ISSUE TITLE
你好，我换成自己的数据后出现了这样的错：

### ISSUE THREAD

**Issue by mingxixixi** [fastnlp/TENER#1]
assert tag in tags, f"{tag} is not a valid tag in encoding type:{encoding_type}. Please check your " \
AssertionError: i is not a valid tag in encoding type:bmeso. Please check your encoding_type.
是哪里有问题呢？

**Comment by SaintLogos1234** [comment]
原因是你的NER的标注格式是BIO，这个代码的NER标注格式是BMES，你把encoding_type改为bio就能跑了

**Comment by mingxixixi** [comment]
> 原因是你的NER的标注格式是BIO，这个代码的NER标注格式是BMES，你把encoding_type改为bio就能跑了

好的，谢谢

**Comment by s1162276945** [comment]
在Linux下，把encoding_type改为bio还是报“UnicodeDecoderError”
