### ISSUE TITLE
您好我想问一下对测试集计算P\R\F1时的一个小问题？

### ISSUE THREAD

**Issue by xuanzebi** [fastnlp/TENER#11]
我想问下 对于测试集长度长于训练集的训练长度的文本时？对于这部分文本长度比训练集设定的最大训练文本长度长的话，在计算P\R\F1时是怎么进行处理的呀？
是截断成两个句子分别输入模型预测吗？ 
还是对于测试集的文本 长于训练集长度的部分进行抛弃，计算PRF1时候也不用它们？
比如 训练集 最大长度为128，测试集长度是200，那么在计算P R F1时是怎么计算的呢?
是将测试集截断成128从而与预测的128长度进行计算吗

**Comment by yhcc** [comment]
如果模型无法处理这种长度的情况，比较合理的做法可能是直接认为该模型在这个句子上全错。也有部分paper中是使用句号分开，当作更短的句子去做。

**Comment by xuanzebi** [comment]
ok thanks

**Comment by tyistyler** [comment]
您好，关于P/R/F1的计算，我想跟您请教一个问题。

**Comment by tyistyler** [comment]
您好，关于P/R/F1的计算，我想跟您请教一个问题。
TENER模型在计算结果的时候是计算的entity的P/R/F1，还是tags的P/R/F1呢？
