### ISSUE TITLE
你好，请问msra数据集为什么要把train和dev都放在训练集呢

### ISSUE THREAD

**Issue by tyistyler** [fastnlp/TENER#12]
你好，请问在程序中为什么训练集是train_dev，验证集和测试集都是test呢

**Comment by yhcc** [comment]
我之前尝试找了一下以前论文的做法，但发现似乎之前的paper没有拆分train和dev，最后为了和他们直接进行对比，也采用了这种不太合理的方式，历史遗留问题把

**Comment by tyistyler** [comment]
好的，谢谢。另外想请教一下您，应该怎么设置最大的句子长度。现在的输出每个batch的长度是由batch中最长的一句话决定的，请问这个可以修改么？
