### ISSUE TITLE
有关数据集的一个小问题

### ISSUE THREAD

**Issue by tyistyler** [fastnlp/TENER#13]
您好，请问fastnlp中下载的peopleDaily是哪里的数据呢

**Comment by yhcc** [comment]
之前的peopledaily有问题（大概两天以前的都有问题），现在的更新了一下来源。但似乎那个数据非常不可靠，我人工看了一下很多错误。

**Comment by tyistyler** [comment]
好的，谢谢，我以为是98年的人民日报，对比了一下发现并不是
