### ISSUE TITLE
the OOV question

### ISSUE THREAD

**Issue by tyistyler** [fastnlp/TENER#15]
hello，How can the TENER solve the OOV problem, please?

**Comment by TorRient** [comment]
I am also having this problem :(

**Comment by yhcc** [comment]
What do you mean the OOV problem? You mean how to enhance the performance of the OOV entity?

**Comment by tyistyler** [comment]
Sorry, I didn't make it clear.

**Comment by tyistyler** [comment]
Sorry, I didn't make it clear.
I want to know how the char embedding and word embedding working?
for example, in weibo dataset ,one is "科技全方位... ",and the char embedding+word embedding is like "科+科技"，“技+技全”，“全+全方”,etc? or others,
thanks

**Comment by yhcc** [comment]
Tener does not use word embedding, it uses char + bigram embedding as your example ("科+科技"，“技+技全”，“全+全方").

**Comment by tyistyler** [comment]
thanks, and if Tener doesnt find the bigrams, like ("char + <eos>"), if it mapping to "unknown"?

**Comment by yhcc** [comment]
Yes, it depends, if this unfound bigram/char is in the train set, it will be initialized with a random vector; if the unfound bigram/char is in the dev or test set, it will use <unk>.
