### ISSUE TITLE
Memory out 问题

### ISSUE THREAD

**Issue by susoooon** [fastnlp/TENER#19]
使用中文数据集，train.txt大小50M，BIO标注法，更改数据路径和模型路径，以及BSEM为BIO,其他没有变动。使用python train_tenser_cn.py dataset ontonotes 即使是batchsize=1，仍会报错。
RuntimeError: CUDA out of memory. Tried to allocate 57.83 GiB (GPU 0; 8.00 GiB total capacity
windows和Linux测试，出现同样问题。
torch=1.5.1
fastnlp=0.5.5
prettytable=0.7.2

**Comment by yhcc** [comment]
你先check一下是不是句子太长了，如果不是这个问题的话；然后再试一下把pytorch降级到1.4或更以下。我们最近发现pytorch 1.5好像和fastNLP有点不match.

**Comment by susoooon** [comment]
谢谢，应该是句子太长了，之前用Bert有强制截断所以没发现这个问题。

**Comment by yhcc** [comment]
好的
