### ISSUE TITLE
将代码放到Linux平台，使用自己的BIO数据，报UnicodeDecoderError

### ISSUE THREAD

**Issue by s1162276945** [fastnlp/TENER#2]
将代码放到Linux平台，使用自己的BIO数据，报“UnicodeDecoderError”，但是我检查了数据集，字和标签之间用空格和\t都测试了，还是报相同的错误，请问有什么办法可以解决吗。

**Comment by s1162276945** [comment]
把encoding_type改为bio依然不起作用

**Comment by yhcc** [comment]
看报错应该是编码问题，可能你的数据不是utf-8的。建议使用fastNLP自动下载数据，将train_tener_cn.py代码按照如下更改(从88行到93行)
![image](https://user-images.githubusercontent.com/22529082/70766588-2f5c4780-1d99-11ea-824c-8d7230344e51.png)

**Comment by s1162276945** [comment]
好的，我试一下，谢谢你
