### ISSUE TITLE
关于PE向量的问题，为什么要shift?以及为什么要transpose_shift？是为了计算R中的t-j吗

### ISSUE THREAD

**Issue by LLLLLLoki** [fastnlp/TENER#21]
如题

**Comment by yhcc** [comment]
shift是为了节省显存，可以参考 [Music Transformer](https://arxiv.org/pdf/1809.04281v3.pdf) . tranpose_shift是tener论文里没有写的，我实践中发现这个对结果有positive的影响，所以就加上了，这一项实际上想达到的目的是让key具备relative的感知能力。

**Comment by LLLLLLoki** [comment]
谢谢回答
