### ISSUE TITLE
reproducing the results on the paper

### ISSUE THREAD

**Issue by seyeeet** [fastnlp/TENER#32]
Thanks for sharing the code,
can you please share arguments that has been used for training, specifically in the paper propose a modified version of positional encoding but I see that it is set to use None in the file.
Thanks for your help.

**Comment by yhcc** [comment]
``pos_embed=None`` means the model does not use the absolute position embedding (The model is set to use the relative position embedding.). Hyper-parameters are provided in the training file for each dataset.
