### ISSUE TITLE
OntoNotes4.0在哪里下载呢？

### ISSUE THREAD

**Issue by s1162276945** [fastnlp/TENER#6]
作者你好，请问OntoNotes4.0是在哪里下载呢，我只看到https://github.com/yhcc/OntoNotes-5.0-NER
`RuntimeError: Ontonotes cannot be downloaded automatically, you can refer https://github.com/yhcc/OntoNotes-5.0-NER to download and preprocess.`

**Comment by yhcc** [comment]
这是收费数据集

**Comment by s1162276945** [comment]
> 这是收费数据集

好的，明白了。
