### ISSUE TITLE
请问train.all.bmes 这种格式的文件怎么找？

### ISSUE THREAD

**Issue by kcjevin** [fastnlp/TENER#9]
您好，我正在学习您的tener。里面发现WeiboNER/train.all.bmes 这种格式的文件。缺少。可是我找了一下，weibo的 标注，没看的这种标注的。
介绍里的 是 
科	O
技	O
全	O
方	O
位	O
资	O
讯	O
智	O

可是 bmes是什么呢？怎么获取，或怎么标注出来？
谢谢

**Comment by yhcc** [comment]
可以通过
from fastNLP.io import WeiboNER
data_bundle = WeiboNERPipe(encoding_type='bioes').process_from_file()
